# Generated by Django 5.0.7 on 2024-07-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
    ]
