# Generated by Django 5.0.7 on 2024-07-17 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_producto_descripcion_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='purchase_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
