# Generated by Django 5.0.7 on 2025-02-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_descripcion_producto_imagen_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
