# Generated by Django 5.0.7 on 2024-07-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_descripcion_producto_imagen_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='productos/'),
        ),
    ]
