# Generated by Django 5.0.7 on 2025-02-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
