# Generated by Django 5.0.7 on 2024-07-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_producto_imagen_data_producto_link_and_more'),
    ]

    operations = [
            migrations.RemoveField(
            model_name='producto',
            name='link',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
