# Generated by Django 5.0.7 on 2025-02-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_producto_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='specifications',
        ),
    ]
